service: customers-crud
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Scan
      Resource: "*"
  environment:
    TABLE_NAME: 'customers'

functions:
  listCustomers:
    handler: list.main
    events:
    - http:
        path: customers
        method: get
  
  createCustomers:
    handler: create.main
    events:
    - http:
        path: customers
        method: post

  deleteCustomers:
    handler: delete.main
    events:
    - http:
        path: customers/{id}
        method: delete

  updateCustomers:
    handler: update.main
    events:
    - http:
        path: customers/{id}
        method: put
  
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customers
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1