service: translate-text
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  translateText:
    handler: handler.translateText
    events:
     - http:
        path: translate
        method: get
