service: upload-file-to-s3-bucket
frameworkVersion: '2'

plugins:
 - serverless-offline

custom:
  bucket: bucketName

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "*"

functions:
  main:
    handler: handler.main
    events:
     - http:
        path: send
        method: post