service: upload-file-to-s3-bucket
frameworkVersion: '2'

plugins:
 - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  main:
    handler: handler.main
    events:
     - http:
        path: send
        method: post