service: service-06-search-zip-code-and-save
frameworkVersion: '2'

plugins:
 - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    TABLE_NAME: 'test_db'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Put
        - dynamodb:PutItem
      Resource: "*"

functions:
  main:
    handler: handler.main
    events:
      - http:
         path: search/{zipcode}
         method: get

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: test_db
        AttributeDefinitions:
          - AttributeName: cep
            AttributeType: S
        KeySchema:
          - AttributeName: cep
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1