service: functions
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - Rekognition:detectLabels
      Resource: "*" 

functions:
  img-analyse:
    handler: handler.analyse
    # events: 
    #   - http:
    #       path: analyse
    #       method: get
          
