service: translate-text
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - translate:TranslateText
        - comprehend:DetectDominantLanguage
      Resource: "*"

functions:
  translateText:
    handler: handler.translateText
    events:
     - http:
        path: translate
        method: get
